# Generated by Django 3.1.3 on 2020-11-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20200418_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cant_abs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cant_cnc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cant_fdm',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cant_litro_resina',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cant_petg',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cant_pla',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cant_printerSLA_DLP',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cant_tpu',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='diametro_filamento',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='espesor_acrilico',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='espesor_plied_madera',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='espesor_pvc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_3d',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_cnc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='m2_acrilico',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='m2_plied_madera',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='m2_pvc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='materiales_cnc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tipo_resina',
        ),
    ]
